config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: :login
  post 'logout', to: 'sessions#destroy', as: :logout
  get 'terms-of-service', to: 'pages#terms_of_service', as: 'terms_of_service'
  get 'privacy-policy', to: 'pages#privacy_policy', as: :privacy_policy

  resources :users, only: [:new, :create, :destroy] do
    collection do
      get 'activate/:token', to: 'users#activate', as: 'activate_user'
      post 'register_email', to: 'users#register_email', as: 'registration'
      post 'complete_registration/:token', to: 'users#complete_registration', as: 'complete_registration'
      post 'resend_activation_mail/:id', to: 'users#resend_activation_mail', as: 'resend_activation_mail'
    end
  end

  resources :diaries do
    member do
      get 'processing', to: 'diaries#processing'
    end
    collection do
      get 'date/:date', to: 'diaries#redirect_to_diary_or_new', as: :redirect_to_diary_or_new
    end
    resources :videos, only: [] do
      member do
        get 'status', to: 'videos#status', as: 'status_video'
      end
      # ここでメソッドのエンドポイントを設定
      post 'media_convert_callback/:job_id', to: 'videos#media_convert_callback', as: 'media_convert_callback'
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
  root "top#index"
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <% bootstrap_class = case key.to_sym
      when :notice then 'alert-success'
      when :alert then 'alert-danger'
      else 'alert-info'
    end %>
    <div class="alert <%= bootstrap_class %>"><%= value %></div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="footer-links">
      <li><%= link_to '利用規約', terms_of_service_path %></li>
      <li><%= link_to 'プライバシーポリシー', privacy_policy_path %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-brand mx-auto">
        <%= link_to (logged_in? ? diaries_path : root_path) do %>
          <%= image_tag "logo.png", alt: "Music Diary App", height: "40" %>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav ms-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= button_to 'ログアウト', logout_path, method: :post, class: 'nav-link', form_class: 'logout-button', data: { turbo: false } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music Diary App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="wrapper">
    <div class="content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>